### ISSUE TITLE
Path is a directory: rm returned EISDIR (is a directory)

### ISSUE THREAD

**Issue by haiweilian** [xianyunleo/electron-asar-updater-pro#1]
## 复现

第一次更新 app.asar 时成功，第二次在删除旧 update.asar 错误，似乎被识别为文件夹？

https://github.com/xianyunleo/electron-asar-updater-pro/blob/36d98548fdb94a090e680593d8291dc2b1779cf0/src/index.js#L148

## 日志

![image](https://github.com/xianyunleo/electron-asar-updater-pro/assets/34850199/ebbdefd9-066b-4361-b0b5-a2c92f3ed922)

```sh
admin@qiantai MINGW64 ~/AppData/Local/Programs/update-example
$ ./update-example.exe

Checking for update
Update for version 9.1.0 is not available (latest version: 9.0.0, downgrade is disallowed).
Updater:  AppDir: C:\Users\admin\AppData\Local\Programs\update-example
14:47:16.513 > [ electron-asar-updater-pro ] AppDir: C:\Users\admin\AppData\Local\Programs\update-example
Updater:  Check:appVersion:9.1.0
14:47:16.520 > [ electron-asar-updater-pro ] Check:appVersion:9.1.0
Updater:  Moving
14:47:19.900 > [ electron-asar-updater-pro ] Moving
Updater:  canWriteResources true
14:47:19.914 > [ electron-asar-updater-pro ] canWriteResources true
Updater:  Copy C:\Users\admin\AppData\Roaming\update-example\update.asar to C:\Users\admin\AppData\Local\Programs\update-example\resources\app.asar
14:47:19.915 > [ electron-asar-updater-pro ] Copy C:\Users\admin\AppData\Roaming\update-example\update.asar to C:\Users\admin\AppData\Local\Programs\update-example\resources\app.asar

admin@qiantai MINGW64 ~/AppData/Local/Programs/update-example
$ ./update-example.exe

Checking for update
Update for version 9.1.0 is not available (latest version: 9.0.0, downgrade is disallowed).
Updater:  AppDir: C:\Users\admin\AppData\Local\Programs\update-example
14:47:28.767 > [ electron-asar-updater-pro ] AppDir: C:\Users\admin\AppData\Local\Programs\update-example
Updater:  Check:appVersion:9.1.0
14:47:28.771 > [ electron-asar-updater-pro ] Check:appVersion:9.1.0
// filePath C:\Users\admin\AppData\Roaming\update-example\update.asar
Updater:  Download Error,SystemError [ERR_FS_EISDIR]: Path is a directory: rm returned EISDIR (is a directory) \\?\C:\Users\admin\AppData\Roaming\update-example\update.asar
14:47:31.907 > [ electron-asar-updater-pro ] Download Error,SystemError [ERR_FS_EISDIR]: Path is a directory: rm returned EISDIR (is a directory) \\?\C:\Users\admin\AppData\Roaming\update-example\update.asar
(node:18948) UnhandledPromiseRejectionWarning: Error: Download Error,SystemError [ERR_FS_EISDIR]: Path is a directory: rm returned EISDIR (is a directory) \\?\C:\Users\admin\AppData\Roaming\update-example\update.asar
    at Updater.update (C:\Users\admin\AppData\Local\Programs\update-example\resources\app.asar\node_modules\electron-asar-updater-pro\src\index.js:108:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\admin\AppData\Local\Programs\update-example\resources\app.asar\out\main\index.js:25:9
(Use `update-example --trace-warnings ...` to show where the warning was created)
(node:18948) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
a
```

**Comment by xianyunleo** [comment]
请先使用 2.0.x版本
或者自己项目代码手动删除这个文件
后续修复

**Comment by xianyunleo** [comment]
@haiweilian 


已在v2.1.1中修复 https://github.com/xianyunleo/electron-asar-updater-pro/commit/6e9a114bd291429a71296bd11a441fadaf487e1f

**Comment by haiweilian** [comment]
ok, it work
